goliath/urls.py
# -*- coding: utf-8 -*-
"""goliath URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.contrib import admin

from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^_nimda/', admin.site.urls),
    # 商户(user)体系
    url(r'^merchant/', include('merchant.urls', namespace='merchant')),
    # 库存体系
    url(r'^inventory/', include('inventory.urls', namespace='inventory')),
    # 库存历史记录
    url(r'^history/', include('history.urls', namespace='history')),
    # 验证码
    url(r'^captcha/', include('captcha.urls')),
]

merchant/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import (LoginView,
                    LogoutView,
                    RegisterView)

app_name = 'merchant'
urlpatterns = [
    # 登录
    url(r'^login/', LoginView.as_view(), name='login'),
    # 登出
    url(r'^logout/', login_required(LogoutView.as_view()), name='logout'),
    # 注册
    url(r'^register/', RegisterView.as_view(), name='register'),
]

templates/base.html
{% load static %}
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>优宜巧购共享库</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/iconfont.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/react-table-v6@latest/react-table.css" />
</head>

<body>
    <!-- nav-bar -->
    <header class="header">
        <h3 class="">优宜巧购共享库</h3>
        <nav class="">
            {% if user.is_authenticated %}
            <a class="">欢迎您, {{user.name}}</a>
            <a class="btn btn-primary" href="{% url 'merchant:logout' %}">退出登录</a>
            {% else %}
            <a class="btn btn-outline-primary" href="{% url 'merchant:login' %}">登录</a>
            <a class="btn btn-outline-primary" href="{% url 'merchant:register' %}">注册</a>
            {% endif %}
        </nav>
    </header>
    <div id="main" class="container">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
        <span class="label label-info">v1.5.7</span>
    </div>
    <script src="{% static 'frontend/index.js' %}"></script>
    <script src="{% static 'frontend/react.js' %}"></script>
    <script src="{% static 'frontend/base.js' %}"></script>
</body>

</html>

templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="form-section">
    <form class="form-signin" method="post" action="/merchant/login/">
        {% csrf_token %}
        <span>欢迎登录</span>
        <h1 class="h3 mb-3 font-weight-normal">优宜巧购</h1>
        <h1 class="h3 mb-3 font-weight-normal sub">共享库</h1>
        {% if message %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p>{{ message }}</p>
        </div>
        {% endif %}
        <div class="user-name form-group">
            <label for="inputEmail" class="sr-only">账号</label>
            <i class="iconfont icon-yonghutouxiang"></i>
            {{ login.username }}
        </div>
        <div class="form-group">
            <label for="inputPassword" class="sr-only">密码</label>
            <i class="iconfont icon-mima"></i>
            {{ login.password }}
        </div>
        <button class="btn btn-primary" type="submit">登录</button>
    </form>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="panel panel-default">
    <div class="panel-body">
        {% if message %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p>{{ message }}</p>
        </div>
        {% endif %}
        <div class="form-section">
            <form method="post" class="form-register" action="{% url 'merchant:register' %}">
                {% csrf_token %}
                <div class="form-group">
                    <i class="iconfont icon-yonghutouxiang"></i>
                    {{ forms.username }}
                </div>
                <div class="form-group">
                    <i class="iconfont icon-mima"></i>
                    {{ forms.password }}
                </div>
                <div class="form-group">
                    <i class="iconfont icon-mima"></i>
                    {{ forms.password1 }}
                </div>
                <div class="form-group">
                    <i class="iconfont icon-shouji"></i>
                    {{ forms.mobile }}
                </div>
                <div class="form-group">
                    <i class="iconfont icon-gongsi"></i>
                    {{ forms.name }}
                </div>
                <div class="form-group">
                    <i class="iconfont icon-dingding"></i>
                    {{ forms.dingding}}
                </div>
                <div class="form-group">
                    <i class="iconfont icon-dizhi"></i>
                    {{ forms.address }}
                </div>
                <div class="form-group">
                    <i class="iconfont icon--"></i>
                    {{ forms.email }}
                </div>
                <div class="form-group">
                    <label>验证码: </label>
                    {{ forms.captcha }}
                </div>
                <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}